image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install nodemon
    command: npm i ejs && npm i request && npm i --save mongo && npm i --save morgan && npm i -g nodemon && npm start
